// RECIPES
export const GET_RECIPES_FROM_API = "GET_RECIPES_FROM_API";
export const CREATE_RECIPE = "CREATE_RECIPE";
// SEARCH BY NAME
export const SEARCH_RECIPES_BY_NAME = "SEARCH_RECIPES_BY_NAME";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
// RECIPES TO SHOW
export const SET_RECIPES_TO_SHOW = "SET_RECIPES_TO_SHOW";
// DIETS
export const GET_DIETS_FROM_API = "GET_DIETS_FROM_API";
// FILTERS AND ORDERS
export const CHANGE_FILTER_BY_DIET_TYPES = "CHANGE_FILTER_BY_DIET_TYPES";
export const CHANGE_FILTER_BY_ORIGIN = "CHANGE_FILTER_BY_ORIGIN";
export const CHANGE_ORDER_BY_NAME = "CHANGE_ORDER_BY_NAME";
export const CHANGE_ORDER_BY_HEALT_SCORE = "CHANGE_ORDER_BY_HEALT_SCORE";
export const CLEAR_FILTERS_AND_ORDERS = "CLEAR_FILTERS_AND_ORDERS";
// PAGINATION
export const SET_PAGINATION_TOTAL_RECIPES = "SET_PAGINATION_TOTAL_RECIPES";
export const SET_PAGINATION_RECIPES_PER_PAGE =
  "SET_PAGINATION_RECIPES_PER_PAGE";
export const SET_PAGINATION_TOTAL_PAGES = "SET_PAGINATION_TOTAL_PAGES";
export const SET_PAGINATION_CURRENT_PAGE = "SET_PAGINATION_CURRENT_PAGE";
